[package]
name = "gen"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
bindgen = { version = "=0.59.2", default-features = false, features = ["which-rustfmt"] }
# something that shouldn't generate a commit
tempdir = "0.3.7"
